# Generated by Django 4.2.6 on 2023-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
