# Generated by Django 4.2.6 on 2023-10-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='bio',
            new_name='description',
        ),
    ]
