# Generated by Django 4.2.6 on 2023-10-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_project_featured_inages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_inages',
            new_name='featured_images',
        ),
    ]
