# Generated by Django 4.2.6 on 2023-10-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
