# Generated by Django 4.2.6 on 2023-11-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
